name       : libgeotiff
version    : 1.7.1
release    : 3
source     :
    - https://github.com/OSGeo/libgeotiff/releases/download/1.7.1/libgeotiff-1.7.1.tar.gz : 05ab1347aaa471fc97347d8d4269ff0c00f30fa666d956baba37948ec87e55d6
homepage   : https://github.com/OSGeo/libgeotiff/
license    :
    - BSD-3-Clause
    - MIT
component  : multimedia.library
summary    : A TIFF based interchange format for georeferenced raster imagery
description: |
    libgeotiff is designed to permit the extraction and parsing of the GeoTIFF Key directories, as well as definition and installation of GeoTIFF keys in new files.
builddeps  :
    - pkgconfig(libjpeg)
    - pkgconfig(libtiff-4)
    - pkgconfig(proj)
setup      : |
    %patch -p1 < $pkgfiles/build-shared-library.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/doc
