name       : libgeotiff
version    : 1.7.0
release    : 1
source     :
    - https://github.com/OSGeo/libgeotiff/releases/download/1.7.0/libgeotiff-1.7.0.tar.gz : fc304d8839ca5947cfbeb63adb9d1aa47acef38fc6d6689e622926e672a99a7e
homepage   : https://github.com/OSGeo/libgeotiff/
license    :
    - BSD-3-Clause
    - MIT
component  : multimedia.library
summary    : A TIFF based interchange format for georeferenced raster imagery
description: |
    libgeotiff is designed to permit the extraction and parsing of the GeoTIFF Key directories, as well as definition and installation of GeoTIFF keys in new files.
builddeps  :
    - pkgconfig(libjpeg)
    - pkgconfig(libtiff-4)
    - pkgconfig(proj)
setup      : |
    %patch -p1 < $pkgfiles/build-shared-library.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/doc
